// Code generated by Slice Machine. DO NOT EDIT.

import StudentInfo from './StudentInfo/index.svelte';
import SquadInfo from './SquadInfo/index.svelte';

export const components = {
	leerling_info: StudentInfo,
	squad_info: SquadInfo
};
