// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type LeerlingenDocumentDataSlicesSlice = LeerlingInfoSlice;

/**
 * Content for StudentCollection documents
 */
interface LeerlingenDocumentData {
	/**
	 * Slice Zone field in *StudentCollection*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: leerlingen.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<LeerlingenDocumentDataSlicesSlice>;
}

/**
 * StudentCollection document from Prismic
 *
 * - **API ID**: `leerlingen`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LeerlingenDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<LeerlingenDocumentData>,
	'leerlingen',
	Lang
>;

/**
 * Content for SingleSquad documents
 */
interface SinglesquadDocumentData {
	/**
	 * SquadName field in *SingleSquad*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: singlesquad.squad_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	squad_name: prismic.KeyTextField;
}

/**
 * SingleSquad document from Prismic
 *
 * - **API ID**: `singlesquad`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SinglesquadDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<SinglesquadDocumentData>,
	'singlesquad',
	Lang
>;

type SquadDocumentDataSlicesSlice = SquadInfoSlice;

/**
 * Content for SquadCollection documents
 */
interface SquadDocumentData {
	/**
	 * Slice Zone field in *SquadCollection*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: squad.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SquadDocumentDataSlicesSlice>;
}

/**
 * SquadCollection document from Prismic
 *
 * - **API ID**: `squad`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<SquadDocumentData>,
	'squad',
	Lang
>;

/**
 * Content for SingleStudent documents
 */
interface StudentDocumentData {
	/**
	 * studentName field in *SingleStudent*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: student.student_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	student_name: prismic.KeyTextField;

	/**
	 * github_visual field in *SingleStudent*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: student.github_visual
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	github_visual: prismic.LinkField;

	/**
	 * githubHandle field in *SingleStudent*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: student.github_handle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	github_handle: prismic.LinkField;

	/**
	 * squad field in *SingleStudent*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: student.squad
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	squad: prismic.ContentRelationshipField;
}

/**
 * SingleStudent document from Prismic
 *
 * - **API ID**: `student`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StudentDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<StudentDocumentData>,
	'student',
	Lang
>;

export type AllDocumentTypes =
	| LeerlingenDocument
	| SinglesquadDocument
	| SquadDocument
	| StudentDocument;

/**
 * Primary content in *StudentInfo → Primary*
 */
export interface LeerlingInfoSliceDefaultPrimary {
	/**
	 * studentName field in *StudentInfo → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: leerling_info.primary.student_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	student_name: prismic.KeyTextField;
}

/**
 * Primary content in *StudentInfo → Items*
 */
export interface LeerlingInfoSliceDefaultItem {
	/**
	 * studentRelation field in *StudentInfo → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: leerling_info.items[].student_relation
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	student_relation: prismic.ContentRelationshipField;
}

/**
 * Default variation for StudentInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeerlingInfoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LeerlingInfoSliceDefaultPrimary>,
	Simplify<LeerlingInfoSliceDefaultItem>
>;

/**
 * Slice variation for *StudentInfo*
 */
type LeerlingInfoSliceVariation = LeerlingInfoSliceDefault;

/**
 * StudentInfo Shared Slice
 *
 * - **API ID**: `leerling_info`
 * - **Description**: LeerlingInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeerlingInfoSlice = prismic.SharedSlice<'leerling_info', LeerlingInfoSliceVariation>;

/**
 * Primary content in *SquadInfo → Items*
 */
export interface SquadInfoSliceDefaultItem {
	/**
	 * squadRelation field in *SquadInfo → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: squad_info.items[].squad_relation
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	squad_relation: prismic.ContentRelationshipField;
}

/**
 * Default variation for SquadInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadInfoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	Simplify<SquadInfoSliceDefaultItem>
>;

/**
 * Slice variation for *SquadInfo*
 */
type SquadInfoSliceVariation = SquadInfoSliceDefault;

/**
 * SquadInfo Shared Slice
 *
 * - **API ID**: `squad_info`
 * - **Description**: SquadInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadInfoSlice = prismic.SharedSlice<'squad_info', SquadInfoSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			LeerlingenDocument,
			LeerlingenDocumentData,
			LeerlingenDocumentDataSlicesSlice,
			SinglesquadDocument,
			SinglesquadDocumentData,
			SquadDocument,
			SquadDocumentData,
			SquadDocumentDataSlicesSlice,
			StudentDocument,
			StudentDocumentData,
			AllDocumentTypes,
			LeerlingInfoSlice,
			LeerlingInfoSliceDefaultPrimary,
			LeerlingInfoSliceDefaultItem,
			LeerlingInfoSliceVariation,
			LeerlingInfoSliceDefault,
			SquadInfoSlice,
			SquadInfoSliceDefaultItem,
			SquadInfoSliceVariation,
			SquadInfoSliceDefault
		};
	}
}
